[preface]
== Glossário Rápido

Este glossário rápido contém muitos dos termos relacionados ao bitcoin que são usados nesse livro. Recomendamos que marque essa página para usá-la como uma referência rápida.

endereço (address)::
    A Bitcoin address looks like +1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+. It consists of a string of letters and numbers. It's really an encoded base58check version of a public key 160-bit hash. Just as you ask others to send an email to your email address, you would ask others to send you bitcoin to one of your Bitcoin addresses.

bip::
    _Bitcoin Improvement Proposals_ (em português, Propostas de Melhoria ao Bitcoin). Um conjunto de propostas que membros da comunidade bitcoin enviaram para melhorar o bitcoin. Por exemplo, a BIP-21 é uma proposta para melhorar a estrutura do Identificador Uniforme de Recursos (URI) do bitcoin.

bitcoin::
    O nome da unidade monetária (da moeda), da rede e do software.

bloco (block)::
    Um agrupamento de transações, marcado com um carimbo de data e hora (um _timestamp_) e uma impressão digital do bloco anterior. O cabeçalho do bloco é submetido a _hashing_ para produzir uma prova de trabalho, assim validando as transações. Os blocos válidos são adicionados à blockchain principal através do consenso da rede.

blockchain (cadeia de blocos)::
	Uma lista de blocos validados, cada um ligado ao seu antecessor até chegar ao bloco gênese.

recompensa do bloco/coinbase (block reward ou coinbase reward)::
    Uma quantidade de moedas incluída em cada novo bloco, que serve como uma recompensa da rede ao minerador que encontrou a solução da Prova-de-Trabalho. Aproximadamente a cada quatro anos, ou exatamente a cada 210.000 blocos, a recompensa do bloco é reduzida pela metade (halving). Atualmente a recompensa é de 6,25 BTC por bloco.

Problema dos Generais Bizantinos::
    Um sistema de computador confiável deve ser capaz de lidar com a falha de um ou mais de seus componentes. Um componente com falha pode exibir um tipo de comportamento que frequentemente pode passar despercebido—como enviar informações conflitantes para diferentes partes do sistema. O problema de lidar com esse tipo de falha é expresso de maneira abstrata como o Problema dos Generais Bizantinos.

bloco candidato (candidate block)::
	Um bloco que um minerador ainda está tentando minerar. Ainda não é considerado um bloco válido, pois não contém uma Prova-de-Trabalho válida.

coinbase/dados coinbase (coinbase/coinbase data)::
	Um campo especial usado como entrada única para as transações coinbase. O campo de dados coinbase permite reivindicar a recompensa do bloco e fornece até 100 bytes para dados arbitrários.
	Não deve ser confundido com transação coinbase ou recompensa coinbase.

transação coinbase::
	A primeira transação em um bloco. Sempre criada por um minerador, ela inclui uma única coinbase.
	Não deve ser confundida com coinbase (dados coinbase) ou recompensa coinbase.

armazenamento frio (_cold storage_)::
	Refere-se a manter uma reserva de bitcoin offline. O armazenamento frio é obtido quando as chaves privadas são criadas e armazenadas em um ambiente offline seguro. O armazenamento frio é importante para qualquer pessoa que tenha economias em bitcoin. Os computadores online são vulneráveis a hackers e não devem ser usados para armazenar uma quantidade significativa de bitcoin.

confirmações (confirmations)::
	Assim que uma transação é incluída em um bloco, dizemos que ela tem uma confirmação. Assim que _outro_ bloco é minerado na mesma blockchain, a transação passa a ter duas confirmações, e assim por diante. Seis ou mais confirmações são consideradas como prova suficiente de que uma transação não pode mais ser revertida.

consenso (consensus)::
    Quando vários nós, geralmente a maioria dos nós na rede, têm todos os mesmos blocos em sua melhor cadeia de blocos validada localmente.
    Não deve ser confundido com regras de consenso.

regras de consenso (consensus rules)::
    As regras de validação de bloco que os nós completos seguem para permanecer em consenso com outros nós.
    Não deve ser confundido com consenso.

dificuldade (difficulty)::
	Uma configuração que é definida em toda a rede e controla quanto esforço computacional é necessário para produzir uma prova de trabalho.

reajuste do alvo de dificuldade (difficulty retargeting)::
	Um recálculo da dificuldade que ocorre em toda a rede a cada 2.016 blocos, levando em consideração o poder de _hashing_ dos 2.016 blocos anteriores.

alvo da dificuldade (difficulty target)::
    Uma dificuldade na qual todo o poder computacional da rede encontrará blocos aproximadamente a cada 10 minutos.

gasto duplo (double-spend)::
    O gasto duplo ocorre quando alguém gasta com sucesso uma quantia de dinheiro mais de uma vez. O bitcoin protege contra gastos duplos ao verificar cada transação que é adicionada à cadeia de blocos, certificando-se de que as entradas da transação ainda não tenham sido gastas.

ECDSA::
    O Algoritmo de Assinatura Digital de Curva Elíptica (em inglês _Elliptic Curve Digital Signature Algorithm_ ou ECDSA) é um algoritmo criptográfico usado pelo bitcoin para garantir que os fundos só possam ser gastos pelos seus legítimos proprietários.

nonce extra::
    À medida que a dificuldade de mineração aumentou, os mineradores frequentemente percorriam todos os 4 bilhões de valores do nonce sem encontrar um bloco. Como o script coinbase pode armazenar entre 2 e 100 bytes de dados, os mineradores começaram a usar esse espaço como espaço de nonce extra, permitindo-lhes explorar um intervalo muito maior de valores de cabeçalho de bloco para encontrar blocos válidos.

taxas (fees)::
	O remetente de uma transação geralmente inclui uma taxa para a rede pelo processamento da transação solicitada. A maioria das transações exige uma taxa mínima de 0,5 mBTC.

fork (bifurcação)::
    O fork, também conhecido como fork acidental, ocorre quando dois ou mais blocos têm a mesma altura de bloco, bifurcando a cadeia de blocos (blockchain). Normalmente ocorre quando dois ou mais mineradores encontram blocos quase ao mesmo tempo. Também pode acontecer como parte de um ataque.

bloco gênese (genesis block)::
	O primeiro bloco na blockchain, usado para inicializar a criptomoeda.

halving::
    Um evento de _halving_ (redução pela metade) ocorre quando a recompensa do bloco é cortada pela metade, o que acontece aproximadamente a cada quatro anos (ou precisamente a cada 210.000 blocos). O bitcoin já teve três eventos de _halving_: em 2012 (de 50 para 25 BTC), em 2016 (de 25 para 12,5 BTC) e em 2020 (de 12,5 para 6,25 BTC).

hard fork::
    O hard fork, também conhecido como "mudança causadora de hard fork", é uma divergência permanente na blockchain, que geralmente ocorre quando nós não atualizados não conseguem validar os blocos criados pelo nós atualizados que seguem novas regras de consenso.
    Não deve ser confundido com fork, soft fork, fork do software ou fork do Git.

carteira de hardware::
    Uma carteira de hardware é um tipo especial de carteira de bitcoin que armazena as chaves privadas do usuário em um dispositivo de hardware seguro.

hash::
    Uma impressão digital de alguma entrada binária.

hashlocks::
    Um hashlock é um tipo de trava que restringe o gasto de uma saída até que um dado específico seja revelado publicamente. Os hashlocks têm a propriedade útil de que, uma vez que qualquer hashlock seja aberto publicamente, qualquer outro hashlock protegido usando a mesma chave também pode ser aberto. Isso torna possível criar várias saídas que são todas travadas pelo mesmo hashlock e que se tornam todas gastáveis ao mesmo tempo.

protocolo HD (HD protocol)::
    O protocolo de transferência e criação de chave Determinística Hierárquica (HD) (BIP-32), que permite criar chaves filhas a partir de chaves pais em uma hierarquia.

carteira HD (HD wallet)::
    Carteiras usando o protocolo de criação de chave e de transferência Determinística Hierárquica (Protocolo HD) (BIP-32).

semente (seed) da carteira HD::
    A semente da carteira HD ou semente raiz é um valor potencialmente curto usado como uma semente para gerar a chave privada mestra e o código de cadeia mestre para uma carteira HD.

HTLC::
    Um Contrato de Hash TimeLock ou HTLC é uma classe de pagamentos que usa travas de hash e de tempo (hashlocks e timelocks) para exigir que o receptor de um pagamento ou reconheça o recebimento do pagamento antes de um prazo ao gerar prova criptográfica de pagamento, ou perca a capacidade de reivindicar o pagamento, devolvendo-o para o pagador.

KYC::
    _Conheça seu cliente_ (em inglês, _Know your customer_ ou KYC) é o processo no qual uma empresa identifica e verifica a identidade de seus clientes. O termo também é usado para se referir ao regulamento bancário que rege essas atividades.

LevelDB::
    A LevelDB é uma biblioteca de armazenamento de código aberto baseada em pares de chave-valor com armazento em disco. A LevelDB é uma biblioteca para persistência, leve e de propósito único, com ligações para muitas plataformas.

Lightning Networks (Redes Lightning)::
    A Lightning Network é uma implementação de Contratos Hash Timelock (HTLCs) com canais de pagamento bidirecionais que permitem que os pagamentos sejam roteados com segurança em vários canais de pagamento par-a-par. Isso permite a formação de uma rede onde qualquer par da rede possa pagar a qualquer outro par, mesmo que eles não tenham um canal aberto diretamente entre si.

Locktime::
    O Locktime, ou mais tecnicamente o nLockTime, é a parte de uma transação que indica o primeiro momento no tempo ou o primeiro bloco em que essa transação pode ser adicionada à cadeia de blocos.

mempool::
    The bitcoin Mempool (memory pool) is a collection of all transaction data in a block that have been verified by Bitcoin nodes, but are not yet confirmed.

raiz de merkle (merkle root)::
    O nó raiz de uma árvore de merkle, um descendente de todos os pares de hash na árvore. Os cabeçalhos de bloco devem incluir uma raiz de merkle válida que seja descendente de todas as transações incluídas naquele bloco.

árvore de merkle (merkle tree)::
    Uma árvore que é construída ao se fazer _hashing_ de dados dispostos em pares (as folhas), cujos resultados são dispostos em pares e novamente são submetidos a _hashing_, até permanecer um único hash, que é a raiz de merkle. No bitcoin, as folhas quase sempre são transações de um único bloco.

minerador (miner)::
    Um nó da rede que encontra uma prova de trabalho válida para novos blocos, ao fazer repetidos _hashings_.

recompensa da mineração (mining reward)::
    A recompensa que os mineradores recebem em troca da segurança fornecida pela mineração. Inclui as novas moedas criadas em cada novo bloco, também conhecido como recompensa de bloco ou recompensa coinbase, e as taxas de transação de todas as transações incluídas no bloco.

multiassinatura (multisignature ou multisig)::
    Multiassinatura refere-se à exigência de um número mínimo (M) de chaves (N) para autorizar uma transação M-de-N.

rede (network)::
    A peer-to-peer network that propagates transactions and blocks to every Bitcoin node on the network.

nonce::
    O "nonce" em um bloco de bitcoin é um campo de 32 bits (4 bytes) cujo valor é definido de forma que o hash do bloco contenha uma sequência de zeros iniciais. Os demais campos não podem ser alterados, pois eles possuem um significado definido.

transações off-chain/fora da cadeia::
    Uma transação _off-chain_ é a movimentação de valor fora da cadeia de blocos (da blockchain). Enquanto uma transação _on-chain_&#x2014;geralmente chamada simplesmente de __uma transação__&#x2014;modifica a blockchain e depende da blockchain para determinar sua validade, uma transação _off-chain_ depende de outros métodos para registrar e validar a transação.

código operacional (opcode)::
    Códigos de operação da linguagem Script do bitcoin que adicionam dados ou executam funções em um script pubkey ou um script de assinatura.

protocolo de Ativos Abertos (Open Assets protocol)::
    The Open Assets Protocol is a simple and powerful protocol built on top of the Bitcoin blockchain. It allows issuance and transfer of user-created assets.

OP_RETURN::
    Um código operacional usado em uma das saídas em uma transação OP_RETURN. Não deve ser confundido com uma transação OP_RETURN.

transação OP_RETURN::
    Um tipo de transação que adiciona dados arbitrários a um script pubkey comprovadamente impossível de ser gasto, que os nós completos não precisam armazenar em seu banco de dados de UTXOs. Não deve ser confundida com um código operacional OP_RETURN.

bloco órfão (orphan block)::
    Blocos cujo bloco pai não foi processado pelo nó local, portanto, ainda não podem ser totalmente validados. Não devem ser confundido com bloco obsoleto.

transações órfãs::
    Transações que não podem entrar na _pool_ devido a uma ou mais transações de entrada ausentes.

saída de transação (output)::
    Uma saída (em inglês, _output_), saída de transação ou TxOut é uma saída em uma transação que contém dois campos: um campo de valor para transferir zero ou mais satoshis e um script pubkey para indicar quais condições devem ser cumpridas para que esses satoshis possam sejam gastos posteriormente.

P2PKH::
    Transactions that pay a Bitcoin address contain P2PKH or Pay To PubKey Hash scripts. An output locked by a P2PKH script can be unlocked (spent) by presenting a public key and a digital signature created by the corresponding private key.

P2SH::
    P2SH ou Pay-to-Script-Hash (em português, Paga-para-Hash-de-Script) é um novo tipo poderoso de transação que simplifica muito o uso de scripts de transação complexos. Com o P2SH, o script complexo que detalha as condições para se gastar a saída (o script de resgate) não é apresentado no script de travamento. Em vez disso, inclui-se apenas um hash do script de resgate no script de travamento.

P2SH, endereço::
    Os endereços P2SH são codificações Base58Check do hash de 20 bytes de um script. Eles usam o prefixo de versão "5", o que resulta em endereços codificados por Base58Check que começam com "3". Os endereços P2SH escondem toda a complexidade, para que a pessoa que faz o pagamento não veja o script.

P2WPKH::
    A assinatura de um P2WPKH (Pay-to-Witness-Public-Key-Hash ou Paga-para-Testemunha-de-Hash-de-Chave-Pública) contém as mesmas informações que um pagamento P2PKH, mas está localizada no campo testemunha ao invés do campo scriptSig. O scriptPubKey também é modificado.

P2WSH::
    A diferença existente entre o P2SH e o P2WSH (Pay-to-Witness-Script-Hash ou Paga-para-Testemunha-de-Hash-de-Script) é a mudança do local da prova criptográfica do campo scriptSig para o campo testemunha, assim como o scriptPubKey, que também é modificado.

carteira de papel (paper wallet)::
    No sentido mais específico, uma carteira de papel é um documento que contém todos os dados necessários para gerar qualquer quantidade de chaves privadas de bitcoin, formando uma carteira de chaves. No entanto, as pessoas costumam usar o termo para se referir a qualquer maneira de armazenar bitcoin offline como um documento físico. Esta segunda definição também inclui chaves de papel e códigos resgatáveis.

frase de senha (passphrase)::
    Uma frase de senha (em inglês, _passphrase_) é uma _string_ opcional criada pelo usuário que serve como um fator de segurança adicional protegendo a semente, mesmo quando a semente for comprometida por furto ou roubo. Ela também pode ser usada como uma forma de negação plausível, quando se usa uma frase de senha para abrir uma carteira com uma quantidade menor de fundos, a qual é usada para distrair um criminoso da carteira "verdadeira", que contém a maioria dos fundos.
    
canais de pagamento (payment channels)::
    A micropayment channel or payment channel is a class of techniques designed to allow users to make multiple bitcoin transactions without committing all of the transactions to the Bitcoin blockchain. In a typical payment channel, only two transactions are added to the block chain but an unlimited or nearly unlimited number of payments can be made between the participants.

pool, mineração em (pooled mining)::
    A mineração em pool é uma modalidade de mineração na qual vários clientes geradores contribuem para a geração de um bloco e, em seguida, dividem a recompensa do bloco de acordo com o poder de processamento contribuído.

Proof-of-Stake::
    O Proof-of-Stake (PoS) (em português, Prova de Participação, Prova de Montante ou Prova de Aposta) é um método através do qual a rede de blockchain de uma criptomoeda visa alcançar um consenso distribuído. O Proof-of-Stake pede aos usuários que comprovem a posse de uma certa quantidade de moeda (que é o seu "stake" na moeda).

Prova-de-Trabalho (Proof-of-Work)::
    Um dado que requer computação significativa para ser encontrado. No bitcoin, os mineradores precisam encontrar uma solução numérica para o algoritmo SHA256 que atenda a um alvo que é definido em toda a rede, o alvo de dificuldade.

RIPEMD-160::
    A RIPEMD-160 é uma função de hash criptográfica de 160 bits. A RIPEMD-160 é uma versão reforçada da RIPEMD que tem como resultado um hash de 160 bits, e espera-se que seja segura nos próximos dez anos ou mais.

satoshi::
    Um satoshi é a menor denominação de bitcoin que pode ser registrada na _blockchain_. É o equivalente a 0,00000001 bitcoin e recebe o nome em homenagem ao criador do bitcoin, Satoshi Nakamoto. ((("satoshi")))

Satoshi Nakamoto::
    Satoshi Nakamoto é o nome usado pela pessoa ou pelo grupo de pessoas que projetou o bitcoin e criou sua implementação de referência original, o Bitcoin Core. Como parte da implementação, eles também criaram o primeiro banco de dados de blockchain. No processo, eles foram os primeiros a resolver o problema do gasto duplo em moedas digitais. Sua verdadeira identidade permanece desconhecida.

Script::
    O bitcoin usa um sistema de script para transações. Semelhante ao Forth, o Script é simples, baseado em pilha e é processado da esquerda para a direita. Ele é propositalmente não Turing completo, sem loops.

ScriptPubKey (script pubkey) ::
    Um ScriptPubKey, ou script pubkey, é um script incluído nas saídas que define as condições que devem ser cumpridas para que esses satoshis sejam gastos. Os dados para o cumprimento das condições podem ser fornecidos em um script de assinatura.

ScriptSig (script de assinatura)::
    Um ScriptSig, ou script de assinatura, são os dados gerados por um pagador que quase sempre são usados como variáveis para satisfazer um script pubkey.

chave secreta/chave privada (secret key/private key)::
	O número secreto que destrava os bitcoins enviados para o endereço correspondente. Uma chave pass:[<span class="keep-together">secreta</span>] tem a seguinte aparência:
+
----
5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh
----

Segregated Witness::
    Segregated Witness (em português, Testemunha Segregada) é uma atualização do protocolo Bitcoin no qual os dados de assinatura (a "testemunha") são separados dos dados do remetente/destinatário para otimizar ainda mais a estrutura das transações. A Segregated Witness foi implementada como um soft fork; uma mudança que tecnicamente torna mais restritivas as regras do protocolo do bitcoin.

SHA::
    O Algoritmo de Hash Seguro (em inglês, _Secure Hash Algorithm_ ou SHA) é uma família de funções de hash criptográficas publicadas pelo Instituto Nacional de Padrões e Tecnologia (_National Institute of Standards and Technology_ ou NIST).

SPV (Verificação de Pagamento Simplificada)::
    SPV ou verificação de pagamento simplificada (em inglês, _simplified payment verification_) é um método para verificar se determinadas transações foram incluídas em um bloco, sem precisar fazer o download do bloco inteiro. Este método de verificação é frequentemente usado por clientes leves de bitcoin.

soft fork::
    Um soft fork ou "mudança causadora de soft fork" é uma bifurcação temporária na blockchain que normalmente ocorre quando os mineradores que usam nós não atualizados não seguem uma nova regra de consenso, pois seus nós não conhecem essa nova regra.
    Não deve ser confundido com fork, hard fork, fork de software ou fork do Git.

bloco obsoleto (_stale block_)::
    Um bloco válido que foi minerado com sucesso, mas que não está incluído no ramo principal atual (com a maior Prova-de-Trabalho acumulada), pois algum outro bloco válido foi minerado na mesma altura e teve sua cadeia estendida primeiro. O minerador de um bloco obsoleto não fica com a recompensa do bloco ou as taxas das transações desse bloco. 
    Não deve ser confundido com bloco órfão ou bloco candidato.

timelocks::
    Um timelock é um tipo de trava que restringe o gasto de alguns bitcoins até um determinado período/data no futuro ou uma altura de bloco. Os timelocks são muito usados em contratos de bitcoin, incluindo canais de pagamento e contratos hash time lock (HTLC).

transação (transaction)::
    In simple terms, a transfer of bitcoin from one address to another. More precisely, a transaction is a signed data structure expressing a transfer of value. Transactions are transmitted over the Bitcoin network, collected by miners, and included into blocks, made permanent on the blockchain.

pool de transações (transaction pool)::
    Uma coleção não ordenada de transações que não estão em blocos na cadeia principal, mas para as quais temos transações de entrada.

completude de Turing (Turing completeness)::
    Uma linguagem de programação é chamada de "Turing completa" se ela puder executar qualquer programa que uma máquina de Turing possa executar, dado tempo e memória suficientes.

saída de transação não gasta (unspent transaction output ou UTXO)::
    Uma UTXO é uma saída de transação não gasta que pode ser gasta como uma entrada em uma nova transação.

carteira (wallet)::
    Software that holds all your Bitcoin addresses and secret keys. Use it to send, receive, and store your bitcoin.

WIF - Wallet Import Format (Formato de Importação de Carteira)::
    O WIF ou Wallet Import Format é um formato de intercâmbio de dados projetado para permitir a exportação e a importação de uma chave privada com um sinalizador indicando se ela usa ou não uma chave pública comprimida.

Algumas definições contribuídas foram obtidas sob uma licença CC-BY a partir da https://en.bitcoin.it/wiki/Main_Page[Wiki do bitcoin] ou de outras fontes de documentação de código aberto.