[preface]
== Prefácio

=== Escrevendo o Livro do Bitcoin

((("bitcoin", "benefícios do", id="BCbasicbenefits0")))((("sistemas descentralizados", "bitcoin como")))A primeira vez que ouvi falar em bitcoin foi em meados de 2011. Minha reação imediata foi mais ou menos essa "Pfft! Dinheiro de nerd!" e eu ignorei-o por mais seis meses, sem compreender a sua importância. Esta é uma reação que eu tenho observado com frequência entre muitas das pessoas mais inteligentes que conheço, o que me dá algum consolo. Na segunda vez que me deparei com o bitcoin, em uma lista de discussão, eu decidi ler o seu "manual de instruções" oficial, o _white paper_ escrito por Satoshi Nakamoto, para ver do que se tratava. ((("moedas digitais", "bitcoin vs. outras")))Ainda me lembro do momento em que eu terminei de ler aquelas nove páginas, quando eu percebi que o bitcoin não era simplesmente uma moeda digital, mas uma rede de confiança que também poderia servir de base para aplicações muito mais avançadas do que apenas moedas. Após chegar à conclusão de que "isso não é dinheiro, mas sim uma rede de confiança descentralizada", comecei uma jornada de quatro meses em que passei devorando cada pedaço de informação que eu conseguia encontrar sobre o assunto. Eu me tornei obcecado e encantado, passando 12 ou mais horas por dia colado ao monitor, lendo, escrevendo, programando e aprendendo o máximo que eu podia. Após pular muitas refeições, saí desse período de obsessão nove quilos mais magro e determinado a dedicar-me a trabalhar com bitcoin.

Dois anos depois, após criar várias pequenas startups para explorar serviços e produtos relacionados ao bitcoin, eu decidi que estava na hora de escrever o meu primeiro livro. O bitcoin foi um tópico que me levou a um frenesi de criatividade e que consumiu meus pensamentos; foi a tecnologia mais empolgante que eu encontrei desde que conheci a Internet. Estava na hora de compartilhar minha paixão sobre essa incrível tecnologia com uma audiência mais ampla.

=== Público Alvo

((("público alvo")))Esse livro foi escrito principalmente para programadores. Se você sabe alguma linguagem de programação, esse livro irá ensiná-lo como as moedas criptográficas funcionam, como utilizá-las e como desenvolver softwares que trabalhem com elas. Os primeiros capítulos também são adequados como uma introdução aprofundada ao bitcoin para não programadores—pessoas que queiram entender o funcionamento interno do bitcoin e das criptomoedas.

=== Por Que a Capa do Livro Tem Insetos?

((("sistemas descentralizados", "na natureza")))A formiga cortadeira é uma espécie que exibe um comportamento altamente complexo em um super-organismo de colônia, mas onde cada formiga individualmente opera sob um conjunto de regras simples dirigidas por interação social e pela troca de aromas químicos (feromônios). De acordo com a Wikipédia: "Depois dos humanos, as formigas cortadeiras formam as maiores e mais complexas sociedades animais do planeta Terra". Na verdade, as formigas cortadeiras não comem as folhas, mas as utilizam no cultivo de um fungo, que é a principal fonte de alimento da colônia. Você captou isso? Essas formigas estão fazendo agricultura!

Embora as formigas formem uma sociedade baseada em castas e possuam uma rainha para produzir a prole, não há uma autoridade central ou um líder na colônia de formigas. O comportamento altamente inteligente e sofisticado exibido por uma colônia composta por milhões de membros é uma propriedade que surge a partir da interação dos indivíduos em uma rede social.

A natureza mostra que sistemas descentralizados podem ser versáteis e podem produzir uma complexidade emergente, além de uma sofisticação incrível, tudo isso sem a necessidade de uma autoridade central, hierarquia ou partes complexas.

((("decentralized systems", "benefits of")))Bitcoin is a highly sophisticated decentralized trust network that can support myriad financial processes. Yet, each node in the Bitcoin network follows a few simple mathematical rules. The interaction between many nodes is what leads to the emergence of the sophisticated behavior, not any inherent complexity or trust in any single node. Like an ant colony, the Bitcoin network is a resilient network of simple nodes following simple rules that together can do amazing things without any central coordination.((("", startref="BCbasicbenefits0")))

=== Convenções Usadas neste Livro

((("convenções tipográficas")))As seguintes convenções tipográficas são usadas neste livro:

_Itálico_:: Indica novos termos, URLs, endereços de e-mail, nomes e extensões de arquivos.

+Largura constante+:: Usada para listagem de programas, assim como dentro de parágrafos para se referir a elementos de programas como variáveis e nomes de funções, bancos de dados, tipos de dados, variáveis de ambiente, declarações e palavras-chave.

**`Largura constante em negrito`**:: Mostra comandos ou outro texto que deveria ser digitado literalmente pelo usuário.

_++Largura constante em itálico++_:: Mostra um texto que deveria ser substituído por valores fornecidos pelo usuário, ou valores determinados pelo contexto.


[TIP]
====
Este ícone significa uma dica ou sugestão.
====

[NOTE]
====
Este ícone significa uma nota geral.
====

[WARNING]
====
Esse ícone indica uma mensagem de aviso ou cuidado.
====

=== Exemplos de Códigos

((("exemplos de código, obtendo e usando", id="codeuse00")))Os exemplos são ilustrados em Python, C++ e usando uma linha de comando de um sistema operacional do tipo Unix, como o Linux ou o macOS. Todos os _snippets_ de códigos estão disponíveis no subdiretório _code_ do repositório principal no GitHub (https://github.com/bitcoinbook/bitcoinbook[https://github.com/bitcoinbook/bitcoinbook]). Você pode fazer um _fork_ do código do livro, testar exemplos de códigos ou enviar correções via GitHub.

Todos os _snippets_ de códigos podem ser replicados na maioria dos sistemas operacionais com uma instalação mínima dos compiladores e interpretadores das linguagens correspondentes. Quando necessário, providenciaremos as instruções básicas da instalação e exemplos passo-a-passo do resultado dessas instruções.

Alguns dos _snippets_ de códigos e do _output_ do código foram reformatados para a impressão. Em todos esses casos, as linhas foram divididas por uma barra invertida (\), seguida por um caractere de nova linha. Ao transcrever os exemplos, remova estes dois caracteres e una as linhas novamente, obtendo resultados idênticos aos mostrados no exemplo.

All the code snippets use real values and calculations where possible, so that you can build from example to example and see the same results in any code you write to calculate the same values. For example, the private keys and corresponding public keys and addresses are all real. The sample transactions, blocks, and blockchain references have all been introduced in the actual Bitcoin blockchain and are part of the public ledger, so you can review them on any Bitcoin system.

=== Usando Exemplos de Códigos

Esse livro foi feito para ajudá-lo a fazer seu trabalho. Em geral, se um exemplo de código é oferecido nesse livro, você pode utilizá-lo em seus programas e documentação. Você não precisa entrar em contato conosco para pedir permissão, a menos que esteja reproduzindo uma porção significativa do código. Por exemplo, você não precisa pedir permissão para escrever um programa que utiliza vários pedaços de código deste livro. No entanto, você precisa de permissão para vender ou distribuir um CD-ROM de exemplos dos livros O’Reilly. Você não precisa de permissão para responder alguma dúvida citando esse livro ou um exemplo de código. Para incorporar uma porção significativa de exemplos de códigos deste livro na documentação do seu produto, você precisa de permissão.

((("atribuição")))Nós apreciamos, mas não exigimos, atribuição de créditos. Uma atribuição geralmente inclui o título, autor, editor e ISBN. Por exemplo: “_Mastering Bitcoin_ por Andreas M. Antonopoulos (O’Reilly). Copyright 2017 Andreas M. Antonopoulos, 978-1-491-95438-6.”

((("licenças de código aberto")))Algumas edições deste livro são oferecidas sob uma licença de código aberto, como a https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC], neste caso, sendo aplicados os termos desta licença específica.

Se você acredita que o seu uso dos exemplos de código não se encaixam na categoria de uso justo ou nas permissões citadas acima, sinta-se à vontade para entrar em contato conosco em pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== Endereços e Transações de Bitcoin neste Livro

((("getting started", "warnings and cautions")))((("warnings and cautions", "avoid sending money to addresses appearing in book")))((("keys and addresses", "warnings and cautions")))((("transactions", "warnings and cautions")))((("blockchain applications", "warnings and cautions")))((("QR codes", "warnings and cautions")))The Bitcoin addresses, transactions, keys, QR codes, and blockchain data used in this book are, for the most part, real. That means you can browse the blockchain, look at the transactions offered as examples, retrieve them with your own scripts or programs, etc.

É importante frisar que as chaves privadas que foram usadas para construir os endereços ou estão impressas neste livro ou foram "queimadas". Isso significa que, se você enviar dinheiro para qualquer um desses endereços, o dinheiro será perdido para sempre ou, em alguns casos, qualquer pessoa que puder ler o livro poderá tomar esse dinheiro usando as chaves privadas impressas nele.

[WARNING]
====
NÃO ENVIE DINHEIRO A QUALQUER ENDEREÇO CONTIDO NESTE LIVRO. Seu dinheiro será  tomado por outro leitor ou será perdido para sempre.((("", startref="codeuse00")))
====

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
passo:[<a href="https://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (o antigo Safari Books Online) é um treinamento baseado em associação e uma plataforma de referência para empresas, governos, educadores e indivíduos.
====

Os membros têm acesso a milhares de livros, vídeos de treinamento, caminhos de aprendizado, tutoriais interativos e listas de reprodução selecionadas de mais de 250 editoras, incluindo O’Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, Course Technology, entre outras.

Para mais informações, por favor veja:[<a href="https://oreilly.com/safari" class="orm:hideurl"><em>https://oreilly.com/safari</em></a>].

=== Como Entrar em Contato

((("comentários e dúvidas")))((("informações de contato")))Por favor, envie comentários e perguntas sobre este livro para o editor:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (nos Estados Unidos ou Canadá)</li>
  <li>707-829-0515 (internacional ou local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

Para comentar ou fazer perguntas técnicas sobre este livro, envie um e-mail para pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

Para obter mais informações sobre nossos livros, cursos, palestras e notícias, consulte nosso site no link:$$https://www.oreilly.com$$[].

Nos encontre no Facebook: link:$$https://facebook.com/oreilly$$[]

Nos diga no Twitter: link:$$https://twitter.com/oreillymedia$$[]

Nos assista no Youtube: link:$$https://www.youtube.com/oreillymedia$$[]

[role="pagebreak-before"]
=== Como Entrar em Contato com o Autor

Entre em contato comigo, Andreas M. Antonopoulos, no meu site:
link:$$https://aantonop.com/$$[]

Informações sobre o _Dominando o Bitcoin (Mastering Bitcoin)_, a Edição Aberta e as traduções estão disponíveis em:
link:$$https://bitcoinbook.info/$$[]

Siga-me no Facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[]

Siga-me no Twitter:
link:$$https://twitter.com/aantonop$$[]

Siga-me no LinkedIn:
link:$$https://linkedin.com/company/aantonop$$[]

Muito obrigado a todos os meus colaboradores que apoiam o meu trabalho através de doações mensais. Siga-me no Patreon:
link:$$https://patreon.com/aantonop$$[]

=== Agradecimentos

((("agradecimentos", id="acknowledge0")))Este livro representa os esforços e as contribuições de muitas pessoas. Agradeço por toda ajuda que recebi de amigos, colegas e até desconhecidos, que se juntaram a mim nessa tarefa de escrever o livro técnico definitivo sobre criptomoedas e bitcoin.

É impossível fazer uma distinção entre a tecnologia do bitcoin e a comunidade bitcoin—e este livro é um produto tanto dessa comunidade quanto é sobre a tecnologia. Meu trabalho nesse livro foi encorajado, comemorado. apoiado e recompensado por toda a comunidade bitcoin desde o seu início até o fim. Mais do que tudo, esse livro me permitiu fazer parte de uma comunidade maravilhosa por dois anos e não posso agradecer suficientemente por eu ter sido aceito por essa comunidade. Há um número imenso de pessoas para ser mencionadas pelo nome—pessoas que encontrei em conferências, eventos, seminários, meetups, encontros de pizza e pequenas reuniões, assim como tantos que se comunicam comigo via Twitter, reddit, bitcointalk.org e pelo GitHub e que impactaram esse livro de alguma forma. Cada ideia, analogia, pergunta, resposta e explicação que você encontrar nesse livro foi de algum modo inspirada, testada ou melhorada através da interação com a comunidade. Muito obrigado a todos pelo apoio; esse livro não teria acontecido sem vocês. Serei eternamente grato.

A jornada para se tornar um autor começa, é claro, muito antes do primeiro livro. Minha língua nativa (e também na escola) era o grego, e por isso tive que fazer um curso reparador de redação em inglês ainda no meu primeiro ano da universidade. Sou muito grato a Diana Kordas, minha professora de redação em inglês, que muito me ajudou a construir a confiança e as habilidades que precisei naquele ano. Mais para frente, já como profissional, desenvolvi minhas habilidades em redação técnica sobre _data centers_, escrevendo para a revista _Network World_. Meus agradecimentos a John Dix e John Gallant, que me deram meu primeiro trabalho em redação como colunista na _Network World_, ao meu editor Michael Cooney e à minha colega Johna Till Johnson, que editaram minhas colunas e as tornaram publicáveis. Escrever 500 palavras por semana durante quatro anos me deu experiência suficiente para eventualmente considerar a me tornar um autor.

Obrigado também àqueles que me apoiaram quando enviei à O'Reilly minha proposta de livro, ao enviarem referências e revisarem o esboço. Especificamente, obrigado a John Gallant, Gregory Ness, Richard Stiennon, Joel Snyder, Adam B. Levine, Sandra Gittlen, John Dix, Johna Till Johnson, Roger Ver e Jon Matonis. Um obrigado especial ao Richard Kagan e Tymon Mattozko, que revisaram as primeiras versões da proposta e a Matthew Owain Taylor, que fez a editoração da proposta.

Agradeço a Cricket Liu, autor da obra da O'Reilly _DNS e BIND_, que me apresentou à O'Reilly. Agradeço também a Michael Loukides e Allyson MacDonald da O'Reilly, que trabalharam por meses para ajudar a tornar este livro realidade. Allyson foi especialmente paciente quando os prazos foram perdidos e as entregas atrasadas, conforme a vida interferia em nosso cronograma planejado. Na segunda edição, agradeço a Timothy McGovern por orientar o processo, Kim Cofer por editar com paciência e Rebecca Panzer por ilustrar muitos novos diagramas.

Os primeiros rascunhos dos primeiros capítulos foram os mais difíceis, porque o bitcoin é um assunto difícil de desvendar. Toda vez que puxei uma linha da tecnologia bitcoin, tive que puxar a coisa toda. Repetidamente, fiquei paralisado e um pouco desanimado enquanto lutava para facilitar a compreensão do tópico e criar uma narrativa em torno de um assunto técnico tão denso. Por fim, eu decidi contar a história do bitcoin através das histórias das pessoas que usam o bitcoin e o livro inteiro ficou muito mais fácil de escrever. Devo agradecer ao meu amigo e mentor, Richard Kagan, que me ajudou a desenvolver as histórias e a superar os momentos de bloqueio de escritor. Agradeço a Pamela Morgan, que revisou os primeiros rascunhos de cada capítulo na primeira e na segunda edições do livro e fez as perguntas difíceis para torná-los melhores. Além disso, obrigado aos desenvolvedores do grupo de Meetup _San Francisco Bitcoin Developers_, bem como Taariq Lewis e Denise Terry por ajudarem a testar o material inicial. Agradeço também a Andrew Naugler pelo design do infográfico.

Durante o desenvolvimento do livro, eu disponibilizei os primeiros rascunhos via GitHub e convidei o público para comentar. Mais de uma centena de comentários, sugestões, correções e contribuições me foram enviadas em resposta. Tais contribuições foram reconhecidas e agradecidas publicamente em <<github_contrib>>. Acima de tudo, um agradecimento especial para os editores voluntários do GitHub Ming T. Ngyuen (1ª edição) e Will Binns (2ª edição), que trabalharam incansavelmente para organizar, gerenciar e resolver solicitações de pull e relatos de problemas, assim como realizar correções de bugs no GitHub.

Após finalizado o rascunho do livro, ele passou por diversas rodadas de revisão técnica. Obrigado ao Cricket Liu e Lorne Lantz pelas extensas revisões, comentários e apoio.

Vários desenvolvedores de bitcoin contribuíram com amostras de código, análises, comentários e incentivo. Obrigado a Amir Taaki e Eric Voskuil, por exemplos de trechos de código e muitos ótimos comentários; a Chris Kleeschulte, por contribuir com o apêndice sobre o Bitcore; a Vitalik Buterin e Richard Kiss, pela ajuda na matemática da curva elíptica e nas contribuições de código; a Gavin Andresen, pelas correções, comentários e incentivo; Michalis Kargakis, por comentários, contribuições e redação do btcd; e a Robin Inge, por enviar de erratas melhorando a segunda impressão. Na segunda edição, recebi novamente muita ajuda de muitos desenvolvedores do Bitcoin Core, incluindo Eric Lombrozo, que desmistificou a Segregated Witness, Luke Dashjr, que ajudou a melhorar o capítulo sobre transações, Johnson Lau, que revisou a Segregated Witness e outros capítulos, e muitos outros. Devo agradecimentos a Joseph Poon, Tadge Dryja e Olaoluwa Osuntokun, que explicaram a Lightning Network, revisaram meu texto e responderam minhas dúvidas quando tive dificuldades.

Eu devo o meu amor pelas palavras e livros à minha mãe, Theresa, que me criou em uma casa repleta de livros em cada parede. Minha mãe também me deu meu primeiro computador em 1982, mesmo ela sendo uma tecnófoba assumida. Meu pai, Menelaos, um engenheiro civil que recém publicou seu primeiro livro aos 80 anos de idade, foi quem me ensinou o pensamento lógico e analítico, bem como o amor pela ciência e pela engenharia.

Obrigado a todos vocês por me apoiarem durante esta jornada.

[[github_contrib]]
==== Lançamento do Rascunho Inicial (Contribuições no GitHub)

Muitos colaboradores ofereceram comentários, correções e acréscimos ao rascunho que foi divulgado antecipadamente no GitHub. Obrigado a todos por suas contribuições para este livro.

A seguir está uma lista de contribuidores notáveis do GitHub:

////
Agradecimentos aos contribuidores do Github em um novo arquivo...
////
include::github_contrib.adoc[]