[[ch11]]
== A Segurança do Bitcoin

Proteger o bitcoin é desafiador porque ele não é uma referência abstrata a um valor, como um saldo em uma conta bancária. O bitcoin é bem mais parecido com um dinheiro em espécie digital, ou um ouro digital. Provavelmente você já ouviu a expressão "A posse é nove décimos da lei". Bem, no bitcoin, a posse é dez décimos da lei. A posse das chaves que destravam o bitcoin é equivalente à posse de dinheiro em espécie ou de um pedaço de um metal precioso. Você pode perder, esquecer onde guardou, ser roubado ou acidentalmente dar uma quantia errada para alguém. Em todos esses casos, há pouco que os usuários possam fazer, assim como se eles tivessem deixado cair dinheiro na calçada.

Entretanto, o bitcoin possui capacidades que o dinheiro em espécie, o ouro e as contas bancárias não têm. Como qualquer arquivo de computador, é possível realizar-se um _backup_ (uma cópia de segurança) de uma carteira de bitcoin contendo suas chaves. Ela pode ser armazenada em múltiplas cópias, e até mesmo impressa em papel para fazer um backup offline não digital. Você não pode fazer um backup das suas notas de dinheiro, de ouro ou de suas contas bancárias. O bitcoin é tão diferente de tudo que já existiu, que também precisamos encarar sua segurança de uma maneira diferente daquela que já estamos acostumados.

=== Princípios de Segurança

((("segurança", "princípios de segurança", id="Sprinc11")))((("sistemas descentralizados", "segurança dos")))O princípio fundamental do bitcoin é a descentralização e isso traz implicações importantes para a sua segurança. Um modelo centralizado, como o de um banco tradicional ou de uma rede de pagamentos, depende de controles de acesso e de verificações de segurança para manter o sistema livre de criminosos. Em comparação, um sistema descentralizado como o bitcoin atribui a responsabilidade e o controle aos usuários. Como a rede é baseada em Prova-de-Trabalho, e não em controle de acesso, a rede pode ser aberta, não exigindo criptografia para o tráfego de bitcoins.

Em uma rede de pagamentos tradicional, como um sistema de cartões de crédito, o pagamento possui uma ponta aberta, pois ele contém o identificador privado do usuário (o número do cartão de crédito). Após a cobrança inicial, qualquer pessoa com acesso ao identificador pode repetidamente "sacar" fundos e fazer cobranças ao dono do cartão. Em função disso, a rede de pagamentos precisa ser protegida de ponta a ponta com criptografada e deve garantir que nenhum intruso ou intermediário possa comprometer o tráfego de pagamentos, quando eles estiverem em trânsito ou estiverem armazenados (em repouso). Se um criminoso burlar o controle de acesso ao sistema, ele pode comprometer as transações atuais _e também_ os tokens de pagamento, os quais podem ser usados para criar novas transações. Ou, pior ainda, quando os dados dos consumidores são comprometidos, os consumidores são expostos a roubo de identidade e devem tomar medidas para prevenir o uso fraudulento de suas contas comprometidas.

Com o bitcoin, a história é completamente diferente. Uma transação de bitcoin autoriza somente uma quantia específica e somente para um destinatário específico, além de não poder ser forjada ou modificada. Ela não revela nenhuma informação privada, como as identidades dos usuários, e não pode ser utilizada para autorizar pagamentos adicionais. Dessa forma, uma rede de pagamentos de bitcoin não precisa ser criptografada ou protegida de bisbilhoteiros. De fato, você pode transmitir transações de bitcoin usando um canal público aberto, como redes Wi-Fi sem senha ou Bluetooth, sem comprometer a segurança da transação.

O modelo de segurança descentralizado do bitcoin coloca muito poder nas mãos dos usuários. E com esse poder, vem a responsabilidade de manter o sigilo das chaves. Para a maioria dos usuários isso não é uma tarefa fácil, especialmente em dispositivos de uso geral como smartphones ou laptops conectados à Internet. Embora o modelo descentralizado do bitcoin impeça o tipo de comprometimento em massa observado com os cartões de crédito, muitos usuários não são capazes de guardar suas chaves com a devida segurança e acabam sendo hackeados, um de cada vez.


==== Desenvolvendo Sistemas Bitcoin de Maneira Segura

((("sistemas descentralizados", "bitcoin como")))O princípio mais importante para os desenvolvedores do bitcoin é a descentralização. A maioria dos desenvolvedores estão acostumados com modelos de segurança centralizados e podem ter a tentação de aplicar estes modelos em seus aplicativos de bitcoin, com resultados desastrosos.

A segurança do bitcoin depende do controle descentralizado das chaves e da validação independente das transações pelos mineradores. Se você quiser alavancar a segurança do bitcoin, você precisa se assegurar de que você persiste dentro do modelo de segurança do bitcoin. Em termos simples: não retire dos usuários o controle das chaves e não realize transações fora da blockchain.

Por exemplo, muitas das primeiras exchanges de bitcoin concentravam todos os bitcoins dos usuários em uma única carteira "quente" que tinha as chaves armazenadas em um único servidor. Esse tipo de design retira o controle dos usuários e centraliza o controle das chaves em um único sistema. Muitos destes sistemas foram hackeados, com consequências desastrosas para seus clientes.

((("transactions", "off blockchain")))((("off-blockchain transactions")))Another common mistake is to take transactions "off blockchain" in a misguided effort to reduce transaction fees or accelerate transaction processing. An "off blockchain" system will record transactions on an internal, centralized ledger and only occasionally synchronize them to the Bitcoin blockchain. This practice, again, substitutes decentralized bitcoin security with a proprietary and centralized approach. When transactions are off blockchain, improperly secured centralized ledgers can be falsified, diverting funds and depleting reserves, unnoticed.

A menos que você esteja preparado para investir pesado em segurança operacional, múltiplas camadas de controle de acesso e auditorias (como os bancos tradicionais fazem), você deveria pensar com muito cuidado antes de retirar os fundos do contexto de segurança descentralizada do bitcoin. Mesmo que você tenha condições e disciplina para implementar um modelo de segurança robusto, este tipo de modelo apenas replica o frágil modelo das redes financeiras tradicionais, infestado por roubo de identidade, corrupção e fraude. Para aproveitar o modelo único de segurança descentralizada do bitcoin, você deve evitar a tentação das arquiteturas centralizadas que, embora sejam familiares, acabam comprometendo a segurança do bitcoin.

==== A Raiz de Confiança

((("raiz de confiança")))A arquitetura de segurança tradicional é baseada em um conceito conhecido como a _raiz de confiança_, que é um núcleo de confiança usado como base para a segurança de todo o sistema ou aplicação. A arquitetura de segurança é desenvolvida ao redor da raiz de confiança através de uma série de círculos concêntricos, como as camadas de uma cebola, estendendo a confiança do centro para a periferia. Cada camada usa como suporte a camada interna de maior confiança, usando controles de acesso, assinaturas digitais, criptografia e outros elementos de segurança. Conforme os sistemas de software se tornam mais complexos, aumenta a chance de eles possuírem bugs, os quais podem torná-los vulneráveis a falhas de segurança. Como resultado, quanto mais complexo se torna um sistema de software, mais difícil se torna mantê-lo seguro. O conceito da raiz de confiança garante que a maior parte da confiança seja depositada na parte menos complexa do sistema, ou seja, nas partes menos vulneráveis do sistema, enquanto o software mais complexo é desenvolvido ao redor. Essa arquitetura de segurança é repetida em diferentes escalas, primeiro estabelecendo uma raiz de confiança no interior do hardware de um único sistema, para depois estender essa raiz de confiança no sistema operacional para serviços de maior nível e, finalmente, através de múltiplos servidores dispostos em camadas de círculos concêntricos com diminuição progressiva da confiança.

((("mineração e consenso", "segurança e consenso")))A arquitetura de segurança do bitcoin é diferente. No bitcoin, o sistema de consenso cria um registro público de confiança que é completamente descentralizado. Uma blockchain corretamente validada usa o bloco gênese como a raiz de confiança, construindo uma cadeia de confiança a partir deste bloco até o mais atual. Os sistemas bitcoin podem e devem usar a blockchain como sua raiz de confiança. Ao projetar uma aplicação bitcoin complexa que consiste em serviços em diversos sistemas diferentes, você deve examinar cuidadosamente a arquitetura de segurança de maneira a se assegurar do local onde a confiança está sendo depositada. Em última análise, o único elemento que deve ser considerado explicitamente como confiável é uma blockchain validada em sua totalidade. Se a sua aplicação deposita confiança em qualquer elemento que não seja a blockchain, explicitamente ou implicitamente, isso deveria ser motivo de preocupação, pois abre as portas para uma vulnerabilidade. Um bom método para avaliar a segurança da arquitetura de sua aplicação é considerar cada componente individual e avaliar um cenário hipotético no qual este componente está completamente comprometido e sob o controle de um usuário mal intencionado. Considere cada componente de sua aplicação, um a um, e avalie os impactos que serão causados na segurança geral caso este componente venha a ser comprometido. Se a sua aplicação deixar de ser segura quando um desses componentes for comprometido, isso demonstra que você depositou equivocadamente a confiança nestes componentes. Uma aplicação de bitcoin sem vulnerabilidades deveria ser vulnerável somente a um comprometimento no mecanismo de consenso do bitcoin, significando que a sua raiz de confiança é baseada no elemento mais forte da arquitetura de segurança do bitcoin.

The numerous examples of hacked bitcoin exchanges serve to underscore this point because their security architecture and design fails even under the most casual scrutiny. These centralized implementations had invested trust explicitly in numerous components outside the Bitcoin blockchain, such as hot wallets, centralized ledger databases, vulnerable encryption keys, and similar schemes.((("", startref="Sprinc11")))


=== Melhores Práticas na Segurança do Usuário

((("segurança", "melhores práticas de segurança do usuário", id="Suser11")))((("casos de uso", "melhores práticas de segurança do usuário", id="UCsecurity11")))Por milhares de anos, os seres humanos têm feito uso de sistemas físicos de controle de segurança. Em comparação, a segurança digital tem sido usada há menos de 50 anos. Os sistemas operacionais modernos usados para atividades gerais não são muito seguros e não são adequados para o armazenamento de dinheiro digital. Por estarem sempre conectados à Internet, nossos computadores estão constantemente expostos a ameaças externas. Eles rodam milhares de componentes de softwares desenvolvidos por centenas de programadores diferentes, os quais frequentemente possuem acesso irrestrito aos arquivos do usuário. Um único bug ou código mal-intencionado em um único software, entre os milhares instalados em seu computador, pode ser suficiente para comprometer a segurança do que você digita em seu teclado e de todos os seus arquivos, permitindo que criminosos roubem seus bitcoins armazenados em aplicativos de carteiras. Para complicar, o nível de manutenção necessário para manter o computador livre de vírus e trojans está acima da capacidade da grande maioria dos usuários de computador.

Apesar de décadas de pesquisas e avanços na segurança da informação, os ativos digitais infelizmente ainda são vulneráveis a um adversário determinado. Mesmo os sistemas mais restritos e protegidos, utilizados em empresas de serviços financeiros, agências de inteligência e de defesa, são frequentemente burlados. O bitcoin cria ativos digitais que possuem valor intrínseco, que podem ser roubados e transferidos para novos donos de maneira instantânea e irreversível. Isso cria um forte incentivo para a ação de hackers. Até recentemente, após comprometerem informações de identidade ou tokens de acesso—como cartões de crédito ou contas bancárias—os hackers ainda precisavam convertê-los em valor. E, apesar da dificuldade crescente em se realizar estas atividades, temos vistos os roubos acontecendo cada vez mais. O bitcoin traz um novo aspecto a ser considerado nesse problema, pois agora o dinheiro roubado não precisa mais ser lavado; ele é um valor intrínseco contido em um ativo digital.

Felizmente, o bitcoin também criou incentivos para o aperfeiçoamento da segurança dos computadores. Se antigamente o risco de um computador ser comprometido era vago e indireto, com o bitcoin esse risco se torna claro e óbvio. O fato de manter bitcoins em um computador aumenta a conscientização dos usuários em manterem seus computadores mais seguros. Como resultado direto da proliferação e maior adoção do bitcoin e outras moedas digitais, tem se observado uma evolução nas técnicas de _hacking_ e nas soluções de segurança. Em termos simples, agora os hackers tem um alvo muito tentador, enquanto os usuários têm um bom motivo para se defenderem.

Ao longo dos últimos três anos, como resultado direto da adoção do bitcoin, temos observado grandes inovações na área da segurança da informação, na forma de criptografia em hardware, armazenamento de chaves e carteiras de hardware, tecnologia de multiassinatura e custódia digital. Nas próximas seções, examinaremos as melhores práticas para a segurança do usuário.

==== Armazenamento Físico de Bitcoins

((("armazenamento", "armazenamento físico de bitcoin")))((("carteiras de papel")))((("carteiras", "tipos de", "carteiras de papel")))((("carteiras de papel", see="also wallets")))Como a maior parte dos usuários sente-se muito mais confortável com segurança física do que com segurança da informação, um método muito efetivo para proteger bitcoins é convertê-los para uma forma física. As chaves de bitcoins nada mais são do que longos números. Isso significa que elas podem ser armazenadas em uma forma física, como, por exemplo, impressas em um papel ou gravadas em uma moeda de metal. Dessa maneira, manter a segurança das chaves torna-se tão simples quanto manter seguro um papel com chaves de bitcoin impressas. Um conjunto de chaves de bitcoin impressas em papel é chamado de "carteira de papel" (em inglês, _paper wallet_), e existem muitas ferramentas gratuitas que podem ser usadas para criá-las. Eu pessoalmente mantenho a grande maioria dos meus bitcoins (99% ou mais) armazenados em carteiras de papel, criptografadas com BIP-38, com múltiplas cópias trancadas em cofres. ((("armazenamento frio")))((("armazenamento", "armazenamento frio")))A prática de manter bitcoins offline é conhecida como _armazenamento frio_ (em inglês, _cold storage_) e é uma das técnicas de segurança mais efetivas. Em um sistema de armazenamento frio, as chaves são geradas e armazenadas em um sistema offline (que nunca se conecta à Internet). As chaves são armazenadas em papel (impressas) ou em uma mídia digital, como um pendrive.

==== Carteiras de Hardware

((("carteiras", "tipos de", "carteiras de hardware")))((("carteiras de hardware")))A longo prazo, a segurança do bitcoin terá cada vez mais a forma de carteiras de hardware invioláveis. Diferente dos smartphones ou computadores de mesa, uma carteira de bitcoin de hardware possui apenas um único propósito: armazenar bitcoins de forma segura. Com interfaces limitadas e sem o risco de comprometimento por softwares de múltiplos propósitos, essas carteiras podem fornecer um nível altíssimo de segurança para os usuários comuns, não especialistas. Eu espero ver as carteiras de hardware tornando-se o principal método de armazenamento de bitcoins. Para conhecer um exemplo deste tipo de carteira, veja a http://www.trezor.io/[Trezor].

==== Balanceando o Risco

((("risco, balanceamento e diversificação", seealso="security")))Embora a maioria dos usuários se preocupe, com razão, em evitar que seus bitcoins sejam roubados, existe um risco ainda maior. Arquivos de computador são constantemente perdidos. Se eles contiverem bitcoins, a perda será muito mais dolorosa. Ao usar medidas de segurança para suas carteiras de bitcoin, os usuários devem ter muito cuidado para não exagerarem na proteção e acabarem perdendo suas moedas. Em julho de 2011, uma conhecida organização, responsável por um projeto de divulgação do bitcoin, perdeu quase 7.000 bitcoins. Ao tentar prevenir roubos, os donos da organização implementaram múltiplos backups (cópias de segurança) criptografados. Infelizmente, as chaves da criptografia acabaram sendo perdidas, inutilizando os backups e, assim, fazendo com que uma fortuna fosse perdida. Da mesma forma que enterrar dinheiro no meio do deserto, se você proteger demais seus bitcoins, pode ser que você nunca mais consiga achá-los.

==== Diversificando o Risco

Você carregaria todas as suas economias em notas de dinheiro guardadas na sua carteira? A maioria das pessoas consideraria isso imprudente, no entanto os usuários de bitcoin frequentemente mantêm todos os seus bitcoins em uma única carteira. Ao invés disso, os usuários deveriam distribuir o risco de perdê-los entre múltiplas carteiras de bitcoin, de diferentes tipos. Usuários prudentes mantêm somente uma pequena porção de seus bitcoins, talvez menos de 5%, em uma carteira online ou de smartphone, para usá-los nas compras do dia-a-dia, como "trocados no bolso." O resto deveria ser dividido em diferentes formas de armazenamento, como em uma carteira em desktop e em um armazenamento offline (armazenamento frio).

==== Multiassinatura e Governança

((("multisig addresses")))((("addresses", "multisig addresses")))Whenever a company or individual stores large amounts of bitcoin, they should consider using a multisignature Bitcoin address. Multisignature addresses secure funds by requiring a minimum number of signatures to make a payment. The signing keys should be stored in a number of different locations and under the control of different people. In a corporate environment, for example, the keys should be generated independently and held by several company executives, to ensure no single person can compromise the funds. Multisignature addresses can also offer redundancy, where a single person holds several keys that are stored in different locations.

==== Legado

((("legado")))((("executores de ativos digitais")))((("senhas", "legado e ")))((("segurança", "senhas")))Uma importante consideração sobre segurança frequentemente ignorada é a disponibilidade, especialmente no contexto de invalidez, doença ou morte da pessoa que possui as chaves. Para evitar roubos, frequentemente os usuários de bitcoin são orientados a usarem senhas complexas e a manterem suas chaves em segurança, longe do alcance de terceiros. Infelizmente, essa prática torna quase impossível a recuperação dos bitcoins pela família do usuário nas situações em que o usuário não estiver disponível para destravá-los. Na maioria dos casos, as famílias dos usuários sequer tem conhecimento da existência de poupanças feitas em moeda digital.

Se você tem uma grande quantidade de bitcoins, considere a ideia de compartilhar detalhes de acesso com um familiar de confiança ou com um advogado. Uma estratégia mais complexa para o seu legado pode ser obtida utilizando um acesso multiassinatura ou através de um planejamento de herança com um advogado especializado em ativos digitais.((("", startref="Suser11")))((("", startref="UCsecurity11")))

=== Conclusão

O bitcoin é uma tecnologia complexa, completamente nova e sem precedentes. Ao longo do tempo, desenvolveremos melhores ferramentas e práticas de segurança que serão mais fáceis de serem utilizadas por pessoas leigas. Por enquanto, os usuários do bitcoin podem usar muitas das dicas discutidas aqui para aproveitarem o bitcoin de maneira segura e livre de preocupações.